from __future__ import annotations

"""Core plugin base classes for the Entity framework."""

from pipeline.base_plugins import (
    AdapterPlugin as _AdapterPlugin,
    AutoGeneratedPlugin,
    BasePlugin,
    FailurePlugin as _FailurePlugin,
    PromptPlugin as _PromptPlugin,
    ResourcePlugin as _ResourcePlugin,
    ToolPlugin as _ToolPlugin,
    ValidationResult,
    ReconfigResult,
    ConfigurationError,
)


class ResourcePlugin(_ResourcePlugin):
    """Base class for resource plugins."""


class ToolPlugin(_ToolPlugin):
    """Base class for tool plugins."""


class PromptPlugin(_PromptPlugin):
    """Base class for prompt plugins."""


class AdapterPlugin(_AdapterPlugin):
    """Base class for adapter plugins."""


class FailurePlugin(_FailurePlugin):
    """Base class for failure-handling plugins."""


__all__ = [
    "BasePlugin",
    "ResourcePlugin",
    "ToolPlugin",
    "PromptPlugin",
    "AdapterPlugin",
    "FailurePlugin",
    "AutoGeneratedPlugin",
    "ValidationResult",
    "ReconfigResult",
    "ConfigurationError",
]
