from __future__ import annotations

"""Wrapper base plugin classes for the Entity framework."""

from pipeline.base_plugins.auto import AutoGeneratedPlugin
from pipeline.base_plugins.base import (
    BasePlugin as _BasePlugin,
    ConfigurationError,
    ReconfigResult,
)
from pipeline.base_plugins.plugin_types import (
    AdapterPlugin as _AdapterPlugin,
    FailurePlugin as _FailurePlugin,
    PromptPlugin as _PromptPlugin,
)
from pipeline.base_plugins.resource import ResourcePlugin as _ResourcePlugin
from pipeline.base_plugins.tool import ToolPlugin as _ToolPlugin
from pipeline.validation import ValidationResult


class ResourcePlugin(_ResourcePlugin):
    """Base class for resource plugins."""


class ToolPlugin(_ToolPlugin):
    """Base class for tool plugins."""


class PromptPlugin(_PromptPlugin):
    """Base class for prompt plugins."""


class AdapterPlugin(_AdapterPlugin):
    """Base class for adapter plugins."""


class FailurePlugin(_FailurePlugin):
    """Base class for failure-handling plugins."""


BasePlugin = _BasePlugin

__all__ = [
    "BasePlugin",
    "ResourcePlugin",
    "ToolPlugin",
    "PromptPlugin",
    "AdapterPlugin",
    "FailurePlugin",
    "AutoGeneratedPlugin",
    "ValidationResult",
    "ReconfigResult",
    "ConfigurationError",
]
