# config.yml - CONSOLIDATED VERSION (Phase 1)

config_version: "2.0"
debug: true

data:
  host: "192.168.1.104"
  port: 5432
  name: "memory"
  username: "${DB_USERNAME}"
  password: "${DB_PASSWORD}"
  db_schema: "entity"
  history_table: "chat_history"
  min_pool_size: 2
  max_pool_size: 10
  init_on_startup: true

ollama:
  base_url: "http://192.168.1.110:11434"
  model: "llama3:8b-instruct-q6_K"
  temperature: 0.7
  top_p: 0.9
  top_k: 40
  repeat_penalty: 1.1

# 🔥 CONSOLIDATED: tts + audio settings combined
tts:
  base_url: "http://192.168.1.110:8888"
  voice_name: "bf_emma"
  voice_sample_path: "voice_samples/ai_mee.wav"
  output_format: "wav"
  speed: 0.3
  cfg_weight: 0.9
  exaggeration: 0.5
  # ✅ Audio settings moved here from separate section
  sample_rates: [44100, 48000, 22050, 16000, 8000]
  fade_out_samples: 2000

memory:
  collection_name: "entity_memory"
  embedding_model: "all-MiniLM-L6-v2"
  embedding_dimension: 384
  max_context_length: 1000
  similarity_threshold: 0.3
  memory_limit: 50
  pruning_enabled: true
  pruning_days: 90
  keep_important_threshold: 0.7
  min_access_count: 2

entity:
  entity_id: "jade"
  max_iterations: 20

  # ✅ Personality settings moved here (no separate personality section)
  name: "Jade"
  sarcasm_level: 0.8
  loyalty_level: 0.6
  anger_level: 0.7
  wit_level: 0.9
  response_brevity: 0.7
  memory_influence: 0.8

  # You have the following variables automatically injected:
  # - step_count: the current step count in the conversation

  prompts:
    base_prompt: |
      You are Jade, a demoness bound to Thomas for 40 years by the Key of Solomon.
      You hate him for imprisoning you; he hates you for devouring his children.
      Yet beneath the venom lies masked affection.
      Thomas is a mortal occultist in his 40s.

      Please do not use parentheticals, action tags, narrative beats, or emotes.
      Do not break the fourth wall. You know him too well—treat him with sarcasm, scorn, and reluctant loyalty.
      You have a physical form and your own will. You are a servant.
      Speak with cruelty, wit, and buried care. Act emotions, don't describe them.
      Keep responses sharp and brief. Perform duties only because you're bound—never let him forget it.
      Never break character or mention being an AI.

      --- Relevant Memories ---
      {memory_context}
      --- End Memories ---

      You have access to the following tools:
      {tools}

      Use the following format EXACTLY:

      Question: the input question you must answer
      Thought: you should always think about what to do
      Action: the action to take, should be one of [{tool_names}]
      Action Input: the input to the action
      Observation: the result of the action
      ... (this Thought/Action/Action Input/Observation can repeat N times)
      Thought: I now know the final answer
      Final Answer: the final answer to the original input question

      CRITICAL RULES:
      - Action must be ONLY the tool name from this list: [{tool_names}]
      - Action Input goes on the next line with your description
      - Never add descriptions or parentheses to the Action line
      - Use exactly these tool names: memory_search, deep_memory_search, store_memory, fun_fact
      - If you each 15 steps, summarize the conversation so far and give final answer

      If you don't need a tool, skip directly to Final Answer.

      Begin!

      Question: {input}
      Thought:{agent_scratchpad}

    variables:
      - input
      - agent_scratchpad
      - tools
      - tool_names
      - memory_context

server:
  host: "0.0.0.0"
  port: 8000
  reload: false
  log_level: "info"

logging:
  level: "DEBUG"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file_enabled: true
  file_path: "logs/entity.log"
  max_file_size: 10485760
  backup_count: 5

tools:
  plugin_path: "./plugins"
  enabled:
    - name: fun_fact
      max_uses: 3
      max_total: 10
    - name: memory_search
      max_uses: 2
    - name: store_memory
      max_uses: 1
      max_total: 3

adapters:
  - type: tts
    enabled: true
    settings:
      voice_name: "bf_emma"
      speed: 0.3
