version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg16
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USERNAME:-dev}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-dev}
      POSTGRES_DB: ${DB_NAME:-entity_dev}
    ports:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME:-dev}"]
      interval: 5s
      timeout: 3s
      retries: 5

  ollama:
    build: .
    image: entity-ollama
    privileged: true
    env_file:
      - .env
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

volumes:
  postgres_data:
  ollama_data:
