[tool.poetry]
name = "entity"
version = "0.0.1"
description = "Entity agentic system with PostgreSQL memory"
authors = ["C. Thomas Brittain <cthomasbrittain@hotmail.com>"]
license = "MIT"
readme = "README.md"
package-mode = true

packages = [{ include = "src", from = "." }]


[tool.poetry.urls]
homepage = "https://github.com/Ladvien/entity"
repository = "https://github.com/Ladvien/entity"
documentation = "https://entity.readthedocs.io/en/latest/"


[tool.poetry.dependencies]
python = "^3.13"
pyyaml = "^6.0.2"
rich = "^13.9.4"
requests = "^2.32.4"
pyaudio = "^0.2.14"
scipy = "^1.15.3"
python-dotenv = "^1.1.0"
transformers = "^4.52.4"
asyncpg = "^0.30.0"
fastapi = "0.115.7"
pydantic = "2.10.5"
uvicorn = "^0.34.3"
langchain = "^0.3.25"
langchain-community = "^0.3.25"
langchain-ollama = "^0.2.0"
ollama = "^0.5.1"
httpx = "^0.28.1"
langgraph = "^0.2.0"
langgraph-checkpoint-postgres = "^2.0.21"
sentence-transformers = "^4.1.0"
psycopg = "^3.2.9"
langchain_postgres = { git = "https://github.com/langchain-ai/langchain-postgres.git", branch = "main" }
greenlet = "^3.2.3"


[tool.poetry.group.dev.dependencies]
black = "^25.1.0"
sphinx = "^8.1.3"
myst-parser = "^4.0.1"
sphinx-autobuild = "^2024.10.3"
furo = "^2024.8.6"
sphinx-autoapi = "^3.5.0"
sphinx-autodoc2 = "^0.5.0"
doc-utils = "^0.0.2"
poethepoet = "^0.32.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poe.tasks]
docs = "sphinx-build docs/source docs/build/html"
docs_view = "sphinx-autobuild docs/source docs/build/html"
patch = "poetry version patch"
_publish = "poetry publish --build"
release = ["docs", "patch", "_publish"]
