[tool.poetry]
name = "entity"
version = "0.0.1"
description = "A short description of your package."
authors = ["C. Thomas Brittain <cthomasbrittain@hotmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.urls]
homepage = "https://github.com/Ladvien/entity"
repository = "https://github.com/Ladvien/entity"
documentation = "https://entity.readthedocs.io/en/latest/"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "0.115.7"
uvicorn = "^0.34.3"
langchain = "^0.3.25"
langchain-community = "^0.3.25"
ollama = "^0.5.1"
pydantic = "^2.11.7"
httpx = "^0.28.1"
python-dotenv = "^1.1.0"
langchain-ollama = "^0.3.3"

[tool.poetry.group.dev.dependencies]
black = "^25.1.0"
pytest = "^8.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
start = "main:main"
