from entity.core.plugins import (
    AdapterPlugin,
    InputAdapterPlugin,
    OutputAdapterPlugin,
    Plugin,
    FailurePlugin,
    InfrastructurePlugin,
    PromptPlugin,
    ResourcePlugin,
    ToolPlugin,
    ValidationResult,
)


class AutoGeneratedPlugin(Plugin):  # type: ignore[misc]
    """Placeholder for auto-generated plugins."""

    stages: list[str] = []


__all__ = [
    "Plugin",
    "InfrastructurePlugin",
    "ResourcePlugin",
    "AgentResource",
    "ToolPlugin",
    "PromptPlugin",
    "AdapterPlugin",
    "InputAdapterPlugin",
    "OutputAdapterPlugin",
    "FailurePlugin",
    "AutoGeneratedPlugin",
    "ValidationResult",
]
