from __future__ import annotations

"""Public package entrypoints."""

from common_interfaces.plugins import configure_plugins
from pipeline.agent import Agent
from pipeline.base_plugins import (
    AdapterPlugin,
    AutoGeneratedPlugin,
    BasePlugin,
    PromptPlugin,
)
from pipeline.builder import AgentBuilder
from pipeline.runtime import AgentRuntime
from plugins.builtin.adapters.server import AgentServer

configure_plugins(BasePlugin, PromptPlugin, AdapterPlugin, AutoGeneratedPlugin)

__all__ = ["Agent", "AgentBuilder", "AgentRuntime", "AgentServer"]
