# Code Review Agent Configuration
# Demonstrates Entity framework plugin architecture for code analysis

input:
  - code_reviewer.plugins.input_plugins.CodeInputPlugin:
      supported_extensions: [".py", ".js", ".ts", ".java", ".cpp", ".c", ".h", ".rs", ".go"]
      max_file_size: 1048576  # 1MB
      exclude_patterns: ["__pycache__", "node_modules", ".git", "*.pyc", "dist", "build"]
      include_hidden: false

parse:
  - entity.plugins.examples.keyword_extractor.KeywordExtractor

think:
  - entity.plugins.examples.reason_generator.ReasonGenerator

do:
  # Code analysis happens here - this is where specialized review plugins would go
  # For this example, we use the reasoning from THINK stage

review:
  # Quality assurance and validation plugins would go here

output:
  - entity.plugins.examples.output_formatter.OutputFormatter
