from entity.core.plugins import (
    AdapterPlugin,
    AutoGeneratedPlugin,
    BasePlugin,
    ToolPlugin,
    PromptPlugin,
)
from entity.core.plugin_utils import PluginAutoClassifier, configure_plugins
from pipeline import PipelineStage

configure_plugins(
    BasePlugin, PromptPlugin, AdapterPlugin, AutoGeneratedPlugin, ToolPlugin
)


async def tool_user(ctx):
    await ctx.tool_use("sleep", text="hi")


def test_classifier_detects_tool_use_call():
    plugin = PluginAutoClassifier.classify(tool_user)
    assert plugin.base_class is ToolPlugin
    assert plugin.stages == [PipelineStage.DO]


async def handle_action(ctx, action: str):
    ctx.store("action", action)


def test_classifier_detects_action_param():
    plugin = PluginAutoClassifier.classify(handle_action)
    assert plugin.base_class is ToolPlugin
    assert plugin.stages == [PipelineStage.DO]
