import pytest

from entity.core.plugins import utils as plugin_utils
from entity.core.plugins import (
    Plugin,
    PromptPlugin,
    AdapterPlugin,
    AutoGeneratedPlugin,
    ToolPlugin,
    FailurePlugin,
    ResourcePlugin,
)
from entity.core.decorators import plugin
from entity.core.stages import PipelineStage

# configure plugin registry
plugin_utils.configure_plugins(
    Plugin,
    PromptPlugin,
    AdapterPlugin,
    AutoGeneratedPlugin,
    ToolPlugin,
    FailurePlugin,
    ResourcePlugin,
)


@plugin(stage=PipelineStage.DO)
async def hinted(_context):
    pass


async def _noop(_context):
    pass


def test_plugin_with_hints():
    obj = hinted.__entity_plugin__
    assert obj.stages == [PipelineStage.DO]
    assert obj.base_class is PromptPlugin


def test_plugin_without_hints():
    with pytest.raises(ValueError):
        plugin(_noop)
