from pipeline.base_plugins import (AdapterPlugin, AutoGeneratedPlugin,
                                   BasePlugin, PromptPlugin)
from pipeline.interfaces import PluginAutoClassifier

from entity.core.plugin_utils import configure_plugins

configure_plugins(BasePlugin, PromptPlugin, AdapterPlugin, AutoGeneratedPlugin)


def test_auto_classifier_marks_inferred():
    async def dummy(ctx):
        return "ok"

    plugin = PluginAutoClassifier.classify(dummy)
    assert getattr(plugin, "_auto_inferred_stages", False)
