from entity.core.plugins import (
    AdapterPlugin,
    AutoGeneratedPlugin,
    FailurePlugin,
    Plugin,
    PromptPlugin,
    ResourcePlugin,
    ToolPlugin,
)
from entity.core.plugin_utils import PluginAutoClassifier
from pipeline import PipelineStage

from entity.core.plugin_utils import configure_plugins

configure_plugins(
    Plugin,
    PromptPlugin,
    AdapterPlugin,
    AutoGeneratedPlugin,
    ToolPlugin,
    FailurePlugin,
    ResourcePlugin,
)


def test_auto_classifier_wraps_function():
    async def dummy(ctx):
        return "ok"

    plugin = PluginAutoClassifier.classify(dummy, {"plugin_class": PromptPlugin})
    assert plugin.stages == [PipelineStage.THINK]
    assert plugin.base_class is PromptPlugin
