import pathlib
import sys

sys.path.insert(0, str(pathlib.Path("src").resolve()))

from entity.core import plugin_utils
from entity.core.plugins import (
    Plugin,
    PromptPlugin,
    AdapterPlugin,
    AutoGeneratedPlugin,
    ToolPlugin,
    FailurePlugin,
    ResourcePlugin,
)
from entity.core.decorators import plugin
from entity.core.stages import PipelineStage

# configure plugin registry
plugin_utils.configure_plugins(
    Plugin,
    PromptPlugin,
    AdapterPlugin,
    AutoGeneratedPlugin,
    ToolPlugin,
    FailurePlugin,
    ResourcePlugin,
)


@plugin(stage=PipelineStage.DO)
async def hinted(_context):
    pass


@plugin
async def default(_context):
    pass


def test_plugin_with_hints():
    obj = hinted.__entity_plugin__
    assert obj.stages == [PipelineStage.DO]
    assert obj.base_class is PromptPlugin


def test_plugin_without_hints():
    obj = default.__entity_plugin__
    assert obj.stages == [PipelineStage.THINK]
    assert obj.base_class is PromptPlugin
