from common_interfaces.plugins import configure_plugins
from pipeline.base_plugins import (
    AdapterPlugin,
    AutoGeneratedPlugin,
    BasePlugin,
    PromptPlugin,
)
from pipeline.interfaces import PluginAutoClassifier

configure_plugins(BasePlugin, PromptPlugin, AdapterPlugin, AutoGeneratedPlugin)


def test_auto_classifier_marks_inferred():
    async def dummy(ctx):
        return "ok"

    plugin = PluginAutoClassifier.classify(dummy)
    assert getattr(plugin, "_auto_inferred_stages", False)
