type: object
properties:
  server:
    $ref: ./server.yaml
  plugins:
    $ref: ./user_plugins.yaml
  tool_registry:
    type: object
    properties:
      concurrency_limit:
        type: integer
        default: 5
      cache_ttl:
        type: integer
        nullable: true
    additionalProperties: false
additionalProperties: false
