"""Convenience exports for plugin base classes."""

from pipeline.base_plugins import (
    AdapterPlugin,
    AutoGeneratedPlugin,
    BasePlugin,
    FailurePlugin,
    PromptPlugin,
    ResourcePlugin,
    ToolPlugin,
)

__all__ = [
    "AdapterPlugin",
    "AutoGeneratedPlugin",
    "BasePlugin",
    "FailurePlugin",
    "PromptPlugin",
    "ResourcePlugin",
    "ToolPlugin",
]
