from entity.core.plugins import (
    AdapterPlugin,
    AgentResource,
    BasePlugin,
    FailurePlugin,
    InfrastructurePlugin,
    PromptPlugin,
    ResourcePlugin,
    ToolPlugin,
    ValidationResult,
)


class AutoGeneratedPlugin(BasePlugin):  # type: ignore[misc]
    """Placeholder for auto-generated plugins."""

    stages: list[str] = []


__all__ = [
    "BasePlugin",
    "InfrastructurePlugin",
    "ResourcePlugin",
    "AgentResource",
    "ToolPlugin",
    "PromptPlugin",
    "AdapterPlugin",
    "FailurePlugin",
    "AutoGeneratedPlugin",
    "ValidationResult",
]
