from entity.core.plugins.base import (
    BasePlugin,
    ResourcePlugin,
    ToolPlugin,
    PromptPlugin,
    AdapterPlugin,
    FailurePlugin,
)
from pipeline.validation import ValidationResult


class AutoGeneratedPlugin(BasePlugin):
    """Placeholder for auto-generated plugins."""

    stages = []


__all__ = [
    "BasePlugin",
    "ResourcePlugin",
    "ToolPlugin",
    "PromptPlugin",
    "AdapterPlugin",
    "FailurePlugin",
    "AutoGeneratedPlugin",
    "ValidationResult",
]
