from __future__ import annotations

"""Backward compatibility re-exports for plugin base classes."""

from .base_plugins import (AdapterPlugin, AutoGeneratedPlugin, BasePlugin,
                           ConfigurationError, FailurePlugin, PromptPlugin,
                           ReconfigResult, ResourcePlugin, ToolPlugin,
                           ValidationResult)

__all__ = [
    "AdapterPlugin",
    "AutoGeneratedPlugin",
    "BasePlugin",
    "ConfigurationError",
    "FailurePlugin",
    "PromptPlugin",
    "ReconfigResult",
    "ResourcePlugin",
    "ToolPlugin",
    "ValidationResult",
]
