from __future__ import annotations

"""Backward compatibility layer for legacy imports."""

import sys
from importlib import import_module

from ..base_plugins import (
    AdapterPlugin,
    AutoGeneratedPlugin,
    BasePlugin,
    FailurePlugin,
    PromptPlugin,
    ResourcePlugin,
    ToolPlugin,
)

__all__ = [
    "BasePlugin",
    "PromptPlugin",
    "ResourcePlugin",
    "ToolPlugin",
    "AdapterPlugin",
    "FailurePlugin",
    "AutoGeneratedPlugin",
]

for _sub in ["failure", "resources", "prompts", "tools", "infrastructure"]:
    try:
        mod = import_module(f"plugins.contrib.{_sub}")
    except ModuleNotFoundError:
        continue
    sys.modules[f"pipeline.user_plugins.{_sub}"] = mod
