"""Base plugin types used by the Entity pipeline."""

from ..validation import ValidationResult
from .auto import AutoGeneratedPlugin
from .base import BasePlugin, ConfigurationError, ReconfigResult
from .plugin_types import AdapterPlugin, FailurePlugin, PromptPlugin
from .resource import ResourcePlugin
from .tool import ToolPlugin

__all__ = [
    "BasePlugin",
    "ResourcePlugin",
    "ToolPlugin",
    "PromptPlugin",
    "AdapterPlugin",
    "FailurePlugin",
    "AutoGeneratedPlugin",
    "ValidationResult",
    "ReconfigResult",
    "ConfigurationError",
    "PluginAutoClassifier",
]

if False:  # pragma: no cover - type checking imports
    from ..interfaces import PluginAutoClassifier
else:
    from ..interfaces import PluginAutoClassifier  # type: ignore  # noqa: E402
