from ..validation import ValidationResult
from .base import (
    AdapterPlugin,
    BasePlugin,
    ConfigurationError,
    FailurePlugin,
    PromptPlugin,
    ReconfigResult,
    ResourcePlugin,
    ToolPlugin,
)
<<<<<< codex/enhance-plugin-auto-detection-and-creation
from .base import AutoGeneratedPlugin
=======
from .classifier import PluginAutoClassifier
>>>>>> main

__all__ = [
    "AdapterPlugin",
    "AutoGeneratedPlugin",
    "BasePlugin",
    "ConfigurationError",
    "FailurePlugin",
    "PromptPlugin",
    "ReconfigResult",
    "ResourcePlugin",
    "ToolPlugin",
    "ValidationResult",
    "PluginAutoClassifier",
]
