"""Public re-exports for plugin base classes."""

from ..base_plugins import (
    AdapterPlugin,
    AutoGeneratedPlugin,
    BasePlugin,
    ConfigurationError,
    FailurePlugin,
    PromptPlugin,
    ReconfigResult,
    ResourcePlugin,
    ToolPlugin,
    ValidationResult,
)
from .classifier import PluginAutoClassifier

__all__ = [
    "AdapterPlugin",
    "AutoGeneratedPlugin",
    "BasePlugin",
    "ConfigurationError",
    "FailurePlugin",
    "PromptPlugin",
    "ReconfigResult",
    "ResourcePlugin",
    "ToolPlugin",
    "ValidationResult",
    "PluginAutoClassifier",
]
