from __future__ import annotations

from typing import Any, List, Optional

from ..base_plugins import (
    AutoGeneratedPlugin as _AutoGeneratedPlugin,
    BasePlugin,
    PromptPlugin,
    AdapterPlugin,
    ToolPlugin,
)
from ..stages import PipelineStage


class AutoGeneratedPlugin(_AutoGeneratedPlugin):
    """Wrapper for auto-generated plugins exposed under ``pipeline.plugins``."""

    def __init__(
        self,
        func: Any,
        stages: List[PipelineStage],
        priority: int,
        name: str,
        base_class: Optional[type] = None,
    ) -> None:
        super().__init__(
            func=func,
            stages=stages,
            priority=priority,
            name=name,
            base_class=base_class,
        )
