from __future__ import annotations

import inspect
from typing import Any, Dict, Optional, Type, cast

from ..base_plugins import BasePlugin, PromptPlugin, AdapterPlugin, ToolPlugin
from ..stages import PipelineStage

from .base import AutoGeneratedPlugin


class PluginClassifier:
    """Heuristically determine plugin stage and type."""

    STAGE_KEYWORDS: dict[PipelineStage, set[str]] = {
        PipelineStage.PARSE: {"parse", "validate", "check", "extract"},
        PipelineStage.THINK: {"think", "reason", "analyze", "plan", "decide"},
        PipelineStage.REVIEW: {"review", "filter", "moderate", "clean"},
        PipelineStage.DELIVER: {"send", "deliver", "output", "respond"},
        PipelineStage.DO: {
            "return",
            "response",
            "answer",
            "fetch",
            "call",
            "execute",
            "compute",
        },
    }

    @classmethod
    def classify(
        cls, func: Any, hints: Optional[Dict[str, Any]] | None = None
    ) -> AutoGeneratedPlugin:
        """Return an :class:`AutoGeneratedPlugin` for ``func``."""

        hints = hints or {}
        try:
            source = inspect.getsource(func)
        except OSError:
            source = ""

        text = f"{func.__name__}\n{func.__doc__ or ''}\n{source}".lower()

        stage = PipelineStage.DO
        base: Type[BasePlugin] = ToolPlugin
        for candidate, keywords in cls.STAGE_KEYWORDS.items():
            if any(k in text for k in keywords):
                stage = candidate
                if candidate == PipelineStage.PARSE:
                    base = AdapterPlugin
                elif candidate == PipelineStage.THINK:
                    base = PromptPlugin
                elif candidate in {PipelineStage.REVIEW, PipelineStage.DELIVER}:
                    base = PromptPlugin
                else:
                    base = (
                        ToolPlugin
                        if any(x in text for x in ["use_tool", "execute_tool", "tool"])
                        else PromptPlugin
                    )
                break

        if "stage" in hints:
            stage = PipelineStage.from_str(str(hints["stage"]))
        priority = int(hints.get("priority", 50))
        name = hints.get("name", func.__name__)

        return AutoGeneratedPlugin(
            func=func,
            stages=[stage],
            priority=priority,
            name=name,
            base_class=cast(Type[BasePlugin], base),
        )

    @classmethod
    def classify_and_route(
        cls, func: Any, hints: Optional[Dict[str, Any]] | None = None
    ) -> AutoGeneratedPlugin:
        """Backward-compatible wrapper for :meth:`classify`."""

        return cls.classify(func, hints)
