server:
  host: "0.0.0.0"
  port: 8000
  reload: true
  log_level: "debug"

plugins:
  resources:
    database:
      type: pipeline.plugins.resources.postgres:PostgresResource
      host: "${DB_HOST}"
      port: 5432
      name: "${DB_USERNAME}"
      username: "${DB_USERNAME}"
      password: "${DB_PASSWORD}"
    llm:
      type: pipeline.plugins.resources.llm.unified:UnifiedLLMResource
      provider: ollama
      base_url: "${OLLAMA_BASE_URL}"
      model: "${OLLAMA_MODEL}"
    logging:
      type: pipeline.plugins.resources.structured_logging:StructuredLogging
      level: "DEBUG"
      file_enabled: true
      file_path: "logs/entity.log"
    memory:
      type: pipeline.plugins.resources.memory:MemoryResource
      database:
        type: pipeline.plugins.resources.sqlite_storage:SQLiteStorageResource
        path: ./dev.db
      filesystem:
        type: pipeline.plugins.resources.s3_filesystem:S3FileSystem
        bucket: agent-files
        region: us-east-1
  tools:
    weather:
      type: pipeline.plugins.tools.weather_api_tool:WeatherApiTool
      api_key: "${WEATHER_API_KEY}"
      base_url: "https://api.weather.com"
    calculator:
      type: pipeline.plugins.tools.calculator_tool:CalculatorTool
  adapters:
    http:
      type: pipeline.adapters.http:HTTPAdapter
    cli:
      type: pipeline.adapters.cli:CLIAdapter
  prompts:
    chain_of_thought:
      type: pipeline.plugins.prompts.chain_of_thought:ChainOfThoughtPrompt
      enable_reasoning: true
    conversation_history:
      type: pipeline.plugins.prompts.conversation_history:ConversationHistory
      history_table: chat_history
    memory_retrieval:
      type: pipeline.plugins.prompts.memory_retrieval:MemoryRetrievalPrompt
      max_context_length: 4000
    intent_classifier:
      type: pipeline.plugins.prompts.intent_classifier:IntentClassifierPrompt
      confidence_threshold: 0.8
