server:
  host: "0.0.0.0"
  port: 8000
  reload: true
  log_level: "debug"

tool_registry:
  concurrency_limit: 5
  cache_ttl: 300

plugins:
  resources:
    database:
      type: plugins.builtin.resources.duckdb_database:DuckDBDatabaseResource
      path: ./dev.duckdb
    llm:
      type: plugins.builtin.resources.llm.unified:UnifiedLLMResource
      provider: ollama
      base_url: "${OLLAMA_BASE_URL}"
      model: "${OLLAMA_MODEL}"
      retries: 3
      backoff: 1.0
    memory:
      type: pipeline.resources.memory:Memory
    vector_store:
      type: plugins.builtin.resources.memory_vector_store:MemoryVectorStore
      table: vector_mem
      embedding_model:
        name: dummy
        dimensions: 3
    filesystem:
      type: plugins.builtin.resources.s3_filesystem:S3FileSystem
      bucket: agent-files
      region: us-east-1
    # storage:
    #   type: pipeline.resources.storage_resource:StorageResource
#   storage:
#     type: pipeline.resources.storage_resource:StorageResource
#     database:
#       type: plugins.builtin.resources.postgres:PostgresResource
#       host: localhost
#       port: 5432
#       name: storage_db
#       username: user
#       password: pass
#     vector_store:
#       type: plugins.builtin.resources.pg_vector_store:PgVectorStore
#       dimensions: 768
#       table: embeddings
#     filesystem:
#       type: plugins.builtin.resources.s3_filesystem:S3FileSystem
#       bucket: agent-files
#       region: us-east-1
    cache:
      type: user_plugins.resources.cache:CacheResource
      backend:
        type: pipeline.cache.memory:InMemoryCache
  tools:
    weather:
      type: user_plugins.tools.weather_api_tool:WeatherApiTool
      api_key: "${WEATHER_API_KEY}"
      base_url: "https://api.weather.com"
    calculator:
      type: user_plugins.tools.calculator_tool:CalculatorTool
  adapters:
    http:
      type: plugins.builtin.adapters.http:HTTPAdapter
      stages: [parse, deliver]
      auth_tokens:
        - dev-secret
      rate_limit:
        requests: 60
        interval: 60
      audit_log_path: logs/audit.log
      dashboard: true
    cli:
      type: plugins.builtin.adapters.cli:CLIAdapter
      stages: [deliver]
    logging:
      type: plugins.builtin.adapters.logging:LoggingAdapter
      stages: [deliver]
  prompts:
    chain_of_thought:
      type: user_plugins.prompts.chain_of_thought:ChainOfThoughtPrompt
      enable_reasoning: true
    conversation_history:
      type: user_plugins.prompts.conversation_history:ConversationHistory
      history_table: chat_history
      stages: [parse, deliver]
    memory_retrieval:
      type: user_plugins.prompts.memory_retrieval:MemoryRetrievalPrompt
      max_context_length: 4000
      stages: [think]
    intent_classifier:
      type: user_plugins.prompts.intent_classifier:IntentClassifierPrompt
      confidence_threshold: 0.8
