server:
  host: "0.0.0.0"
  port: 8000
  reload: true
  log_level: "debug"

tool_registry:
  concurrency_limit: 5

breaker_settings:
  database:
    failure_threshold: 3
  external_api:
    failure_threshold: 5
  file_system:
    failure_threshold: 2

plugins:
  # Layer 1 - infrastructure primitives
  infrastructure: {}
  # Layer 2 - resource interfaces built on infrastructure
  resources:
    database:
      type: entity.resources.database:DuckDBResource
      path: ./agent.duckdb
    # vector_store:
    #   type: plugins.builtin.resources.duckdb_vector_store:DuckDBVectorStore
    #   table: vector_mem
    #   embedding_model:
    #     name: dummy
    #     dimensions: 3
    metrics_collector:
      type: entity.resources.metrics:MetricsCollectorResource
  # Layer 3 - canonical agent resources
  agent_resources:
    memory:
      type: entity.resources.memory:Memory
      dependencies: [database]
    llm:
      type: entity.resources.llm:LLM
      provider: echo
    logging:
      type: entity.resources.logging:LoggingResource
    storage:
      type: entity.resources.storage:Storage
  # filesystem:
  #   type: plugins.builtin.resources.s3_filesystem:S3FileSystem
  #   bucket: agent-files
    #   region: us-east-1
    # storage:
    #   type: plugins.builtin.resources.storage_resource:StorageResource
#   storage:
#     type: plugins.builtin.resources.storage_resource:StorageResource
#     database:
#       type: entity.infrastructure.postgres:PostgresInfrastructure
#       host: localhost
#       port: 5432
#       name: storage_db
#       username: user
#       password: pass
#     vector_store:
#       type: plugins.builtin.resources.pg_vector_store:PgVectorStore
#       dimensions: 768
#       table: embeddings
#     filesystem:
#       type: plugins.builtin.resources.s3_filesystem:S3FileSystem
#       bucket: agent-files
#       region: us-east-1
  # Layer 4 - user defined compositions
  custom_resources: {}
  tools:
    calculator:
      type: plugin_library.tools.calculator_tool:CalculatorTool
  adapters: {}
    # http:
    #   type: plugins.builtin.adapters.http:HTTPAdapter
    #   stages: [parse, deliver]
    #   auth_tokens:
    #     - dev-secret
    #   rate_limit:
    #     requests: 60
    #     interval: 60
    #   audit_log_path: logs/audit.log
    #   dashboard: true
    # cli:
    #   type: plugins.builtin.adapters.cli:CLIAdapter
    #   stages: [deliver]
    # logging:
    #   type: entity.resources.logging:LoggingResource
    #   stages: [deliver]
  prompts:
    chain_of_thought:
      type: entity.plugins.prompts.chain_of_thought:ChainOfThoughtPrompt
      enable_reasoning: true
    react:
      type: entity.plugins.prompts.react:ReActPrompt
      max_steps: 3
    conversation_history:
      type: plugin_library.prompts.conversation_history:ConversationHistory
    memory_retrieval:
      type: plugin_library.prompts.memory_retrieval:MemoryRetrievalPrompt
      max_context_length: 4000
      stages: [think]
    intent_classifier:
      type: plugin_library.prompts.intent_classifier:IntentClassifierPrompt
      confidence_threshold: 0.8
