server:
  host: "0.0.0.0"
  port: 8000
  reload: true
  log_level: "debug"

tool_registry:
  concurrency_limit: 5
  cache_ttl: 300

plugins:
  resources:
    database:
      type: plugins.builtin.resources.postgres:PostgresResource
      host: "${DB_HOST}"
      port: 5432
      name: "${DB_USERNAME}"
      username: "${DB_USERNAME}"
      password: "${DB_PASSWORD}"
      retries: 3
      backoff: 1.0
    llm:
      type: plugins.builtin.resources.llm.unified:UnifiedLLMResource
      provider: ollama
      base_url: "${OLLAMA_BASE_URL}"
      model: "${OLLAMA_MODEL}"
      retries: 3
      backoff: 1.0
    memory:
      type: pipeline.resources.memory_resource:MemoryResource
      storage:
        type: plugins.builtin.resources.sqlite_storage:SQLiteStorageResource
        path: ./dev.db
    storage:
      type: pipeline.resources.storage_resource:StorageResource
      filesystem:
        type: plugins.builtin.resources.s3_filesystem:S3FileSystem
        bucket: agent-files
        region: us-east-1
#   storage:
#     type: pipeline.resources.storage_resource:StorageResource
#     database:
#       type: plugins.builtin.resources.postgres:PostgresResource
#       host: localhost
#       port: 5432
#       name: storage_db
#       username: user
#       password: pass
#     vector_store:
#       type: plugins.builtin.resources.pg_vector_store:PgVectorStore
#       dimensions: 768
#       table: embeddings
#     filesystem:
#       type: plugins.builtin.resources.s3_filesystem:S3FileSystem
#       bucket: agent-files
#       region: us-east-1
    cache:
      type: plugins.contrib.resources.cache:CacheResource
      backend:
        type: pipeline.cache.memory:InMemoryCache
  tools:
    weather:
      type: plugins.builtin.tools.weather_api_tool:WeatherApiTool
      api_key: "${WEATHER_API_KEY}"
      base_url: "https://api.weather.com"
    calculator:
      type: plugins.builtin.tools.calculator_tool:CalculatorTool
  adapters:
    http:
      type: plugins.builtin.adapters.http:HTTPAdapter
      auth_tokens:
        - dev-secret
      rate_limit:
        requests: 60
        interval: 60
      audit_log_path: logs/audit.log
      dashboard: true
    cli:
      type: plugins.builtin.adapters.cli:CLIAdapter
    logging:
      type: plugins.builtin.adapters.logging:LoggingAdapter
  prompts:
    chain_of_thought:
      type: plugins.contrib.prompts.chain_of_thought:ChainOfThoughtPrompt
      enable_reasoning: true
    conversation_history:
      type: plugins.builtin.prompts.conversation_history:ConversationHistory
      history_table: chat_history
    memory_retrieval:
      type: plugins.builtin.prompts.memory_retrieval:MemoryRetrievalPrompt
      max_context_length: 4000
    intent_classifier:
      type: plugins.contrib.prompts.intent_classifier:IntentClassifierPrompt
      confidence_threshold: 0.8
