server:
  host: "0.0.0.0"
  port: 8000
  reload: true
  log_level: "debug"

plugins:
  resources:
    database:
      type: pipeline.plugins.resources.postgres:PostgresResource
      host: "localhost"
      port: 5432
      name: "dev_db"
      username: "${DB_USERNAME}"
      password: "${DB_PASSWORD}"
    ollama:
      type: pipeline.plugins.resources.ollama_llm:OllamaLLMResource
      base_url: "http://localhost:11434"
      model: "llama3:8b-instruct-q6_K"
    logging:
      type: pipeline.plugins.resources.structured_logging:StructuredLogging
      level: "DEBUG"
      file_enabled: true
      file_path: "logs/entity.log"
    memory:
      type: pipeline.plugins.resources.memory_resource:SimpleMemoryResource
  tools:
    weather:
      type: pipeline.plugins.tools.weather_api_tool:WeatherApiTool
      api_key: "${WEATHER_API_KEY}"
      base_url: "https://api.weather.com"
    calculator:
      type: pipeline.plugins.tools.calculator_tool:CalculatorTool
  adapters:
    http:
      type: pipeline.adapters.http:HTTPAdapter
  prompts:
    chain_of_thought:
      type: pipeline.plugins.prompts.chain_of_thought:ChainOfThoughtPrompt
      enable_reasoning: true
    memory_retrieval:
      type: pipeline.plugins.prompts.memory_retrieval:MemoryRetrievalPrompt
      max_context_length: 4000
    intent_classifier:
      type: pipeline.plugins.prompts.intent_classifier:IntentClassifierPrompt
      confidence_threshold: 0.8
