server:
  host: "0.0.0.0"
  port: 80
  reload: false
  log_level: "info"

plugins:
  resources:
    database:
      type: user_plugins.postgres:PostgresResource
      host: "${DB_HOST}"
      port: 5432
      name: "${DB_USERNAME}"
      username: "${DB_USERNAME}"
      password: "${DB_PASSWORD}"
      retries: 5
      backoff: 2.0
    llm:
      type: user_plugins.llm.unified:UnifiedLLMResource
      provider: ollama
      base_url: "${OLLAMA_BASE_URL}"
      model: "${OLLAMA_MODEL}"
      temperature: 0.7
      retries: 5
      backoff: 2.0
    logging:
      type: user_plugins.structured_logging:StructuredLogging
      level: "INFO"
      file_enabled: true
      file_path: "logs/entity.log"
    memory:
      type: user_plugins.memory_resource:MemoryResource
      database:
        type: user_plugins.postgres:PostgresResource
        host: "${DB_HOST}"
        port: 5432
        name: "${DB_NAME}"
        username: "${DB_USERNAME}"
        password: "${DB_PASSWORD}"
      filesystem:
        type: user_plugins.s3_filesystem:S3FileSystem
        bucket: agent-files
        region: us-east-1
    cache:
      type: user_plugins.resources.cache:CacheResource
      backend:
        type: pipeline.cache.redis:RedisCache
  tools:
    weather:
      type: user_plugins.tools.weather_api_tool:WeatherApiTool
      api_key: "${WEATHER_API_KEY}"
      base_url: "https://api.weather.com"
      timeout: 30
    calculator:
      type: user_plugins.tools.calculator_tool:CalculatorTool
      precision: 10
  adapters:
    http:
      type: pipeline.adapters.http:HTTPAdapter
      auth_tokens:
        - ${HTTP_TOKEN}
      rate_limit:
        requests: 100
        interval: 60
      audit_log_path: logs/audit.log
      dashboard: false
    cli:
      type: pipeline.adapters.cli:CLIAdapter
  prompts:
    chain_of_thought:
      type: user_plugins.prompts.chain_of_thought:ChainOfThoughtPrompt
      enable_reasoning: true
      max_steps: 5
    conversation_history:
      type: user_plugins.prompts.conversation_history:ConversationHistory
      db_schema: public
      history_table: chat_history
    memory_retrieval:
      type: user_plugins.prompts.memory_retrieval:MemoryRetrievalPrompt
      max_context_length: 4000
      similarity_threshold: 0.7
    intent_classifier:
      type: user_plugins.prompts.intent_classifier:IntentClassifierPrompt
      confidence_threshold: 0.8
