server:
  host: "0.0.0.0"
  port: 80
  reload: false
  log_level: "info"

tool_registry:
  concurrency_limit: 10
  cache_ttl: 600

plugins:
  resources:
    database:
      type: plugins.builtin.resources.postgres:PostgresResource
      host: "${DB_HOST}"
      port: 5432
      name: "${DB_USERNAME}"
      username: "${DB_USERNAME}"
      password: "${DB_PASSWORD}"
      retries: 5
      backoff: 2.0
    llm:
      type: plugins.builtin.resources.llm.unified:UnifiedLLMResource
      provider: ollama
      base_url: "${OLLAMA_BASE_URL}"
      model: "${OLLAMA_MODEL}"
      temperature: 0.7
      retries: 5
      backoff: 2.0
    memory:
      type: pipeline.resources.memory_resource:MemoryResource
      storage:
        type: plugins.builtin.resources.postgres:PostgresResource
        host: "${DB_HOST}"
        port: 5432
        name: "${DB_NAME}"
        username: "${DB_USERNAME}"
        password: "${DB_PASSWORD}"
    storage:
      type: pipeline.resources.storage_resource:StorageResource
      filesystem:
        type: plugins.builtin.resources.s3_filesystem:S3FileSystem
        bucket: agent-files
        region: us-east-1
#   storage:
#     type: pipeline.resources.storage_resource:StorageResource
#     database:
#       type: plugins.builtin.resources.postgres:PostgresResource
#       host: prod-db.example.com
#       port: 5432
#       name: prod_storage
#       username: prod_user
#       password: securepass
#     vector_store:
#       type: plugins.builtin.resources.pg_vector_store:PgVectorStore
#       dimensions: 768
#       table: embeddings
#     filesystem:
#       type: plugins.builtin.resources.s3_filesystem:S3FileSystem
#       bucket: agent-files
#       region: us-east-1
    cache:
      type: user_plugins.resources.cache:CacheResource
      backend:
        type: user_plugins.resources.cache_backends.redis:RedisCache
  tools:
    weather:
      type: plugins.builtin.tools.weather_api_tool:WeatherApiTool
      api_key: "${WEATHER_API_KEY}"
      base_url: "https://api.weather.com"
      timeout: 30
    calculator:
      type: plugins.builtin.tools.calculator_tool:CalculatorTool
      precision: 10
  adapters:
    http:
      type: plugins.builtin.adapters.http:HTTPAdapter
      stages: [parse, deliver]
      auth_tokens:
        - ${HTTP_TOKEN}
      rate_limit:
        requests: 100
        interval: 60
      audit_log_path: logs/audit.log
      dashboard: false
    cli:
      type: plugins.builtin.adapters.cli:CLIAdapter
      stages: [deliver]
  logging:
    type: plugins.builtin.adapters.logging:LoggingAdapter
    stages: [deliver]
  prompts:
    chain_of_thought:
      type: user_plugins.prompts.chain_of_thought:ChainOfThoughtPrompt
      enable_reasoning: true
      max_steps: 5
  conversation_history:
    type: plugins.builtin.prompts.conversation_history:ConversationHistory
    db_schema: public
    history_table: chat_history
    stages: [parse, deliver]
  memory_retrieval:
    type: plugins.builtin.prompts.memory_retrieval:MemoryRetrievalPrompt
    max_context_length: 4000
    similarity_threshold: 0.7
    stages: [think]
  intent_classifier:
    type: user_plugins.prompts.intent_classifier:IntentClassifierPrompt
    confidence_threshold: 0.8
