server:
  host: "0.0.0.0"
  port: 80
  reload: false
  log_level: "info"

plugins:
  resources:
    database:
<<<<<<< HEAD
      type: pipeline.plugins.resources.postgres:PostgresResource
=======
      type: pipeline.resources.postgres_database:PostgresDatabaseResource
>>>>>>> 31c26c6f08f011fda24b488de4c679ad0b2325fd
      host: "${DB_HOST}"
      port: 5432
      name: "${DB_USERNAME}"
      username: "${DB_USERNAME}"
      password: "${DB_PASSWORD}"
    llm:
      type: pipeline.resources.llm.unified:UnifiedLLMResource
      provider: ollama
      base_url: "${OLLAMA_BASE_URL}"
      model: "${OLLAMA_MODEL}"
      temperature: 0.7
    logging:
      type: pipeline.resources.structured_logging:StructuredLogging
      level: "INFO"
      file_enabled: true
      file_path: "logs/entity.log"
    memory:
      type: pipeline.resources.memory_resource:MemoryResource
      database:
<<<<<<< HEAD
<<<<<<< HEAD
        type: pipeline.plugins.resources.postgres:PostgresResource
=======
        # DatabaseResource implementation
        type: pipeline.plugins.resources.postgres_database:PostgresDatabaseResource
>>>>>>> 3bdcdaeeb77504cd22dc3d64ed6d6085c7e6d9bd
=======
        type: pipeline.resources.postgres_database:PostgresDatabaseResource
>>>>>>> 31c26c6f08f011fda24b488de4c679ad0b2325fd
        host: "${DB_HOST}"
        port: 5432
        name: "${DB_NAME}"
        username: "${DB_USERNAME}"
        password: "${DB_PASSWORD}"
      filesystem:
        type: pipeline.resources.s3_filesystem:S3FileSystem
        bucket: agent-files
        region: us-east-1
  tools:
    weather:
      type: pipeline.plugins.tools.weather_api_tool:WeatherApiTool
      api_key: "${WEATHER_API_KEY}"
      base_url: "https://api.weather.com"
      timeout: 30
    calculator:
      type: pipeline.plugins.tools.calculator_tool:CalculatorTool
      precision: 10
  adapters:
    http:
      type: pipeline.adapters.http:HTTPAdapter
    cli:
      type: pipeline.adapters.cli:CLIAdapter
  prompts:
    chain_of_thought:
      type: pipeline.plugins.prompts.chain_of_thought:ChainOfThoughtPrompt
      enable_reasoning: true
      max_steps: 5
    conversation_history:
      type: pipeline.plugins.prompts.conversation_history:ConversationHistory
      db_schema: public
      history_table: chat_history
    memory_retrieval:
      type: pipeline.plugins.prompts.memory_retrieval:MemoryRetrievalPrompt
      max_context_length: 4000
      similarity_threshold: 0.7
    intent_classifier:
      type: pipeline.plugins.prompts.intent_classifier:IntentClassifierPrompt
      confidence_threshold: 0.8
