server:
  host: "0.0.0.0"
  port: 8000
  reload: true
  log_level: "info"

plugins:
  resources:
    database:
      type: plugins.builtin.resources.postgres:PostgresResource
      host: "${DB_HOST}"
      port: 5432
      name: "${DB_USERNAME}"
      username: "${DB_USERNAME}"
      password: "${DB_PASSWORD}"
    llm:
      provider: ollama
      base_url: "${OLLAMA_BASE_URL}"
      model: "${OLLAMA_MODEL}"
    memory:
      type: pipeline.resources.memory:Memory
      dependencies: [database]
    storage:
      type: pipeline.resources.storage_resource:StorageResource
      dependencies: [filesystem]
    cache:
      type: user_plugins.resources.cache:CacheResource
      backend:
        type: pipeline.cache.memory:InMemoryCache
  tools:
    weather:
      type: user_plugins.tools.weather_api_tool:WeatherApiTool
      api_key: "${WEATHER_API_KEY}"
      base_url: "https://api.weather.com"
    calculator:
      type: user_plugins.tools.calculator_tool:CalculatorTool
  adapters:
    http:
      type: plugins.builtin.adapters.http:HTTPAdapter
      auth_tokens:
        - ${HTTP_TOKEN}
      rate_limit:
        requests: 60
        interval: 60
      audit_log_path: logs/audit.log
    cli:
      type: plugins.builtin.adapters.cli:CLIAdapter
    logging:
      type: plugins.builtin.adapters.logging:LoggingAdapter
  prompts:
    chain_of_thought:
      type: user_plugins.prompts.chain_of_thought:ChainOfThoughtPrompt
      enable_reasoning: true
    memory_retrieval:
      type: user_plugins.prompts.memory_retrieval:MemoryRetrievalPrompt
      max_context_length: 4000
    intent_classifier:
      type: user_plugins.prompts.intent_classifier:IntentClassifierPrompt
      confidence_threshold: 0.8
