server:
  host: "0.0.0.0"
  port: 8000
  reload: true
  log_level: "info"

plugins:
  resources:
    database:
<<<<<<< HEAD
      type: pipeline.plugins.resources.postgres:PostgresResource
=======
      type: pipeline.resources.postgres_database:PostgresDatabaseResource
>>>>>>> 31c26c6f08f011fda24b488de4c679ad0b2325fd
      host: "${DB_HOST}"
      port: 5432
      name: "${DB_USERNAME}"
      username: "${DB_USERNAME}"
      password: "${DB_PASSWORD}"
    llm:
      provider: ollama
      base_url: "${OLLAMA_BASE_URL}"
      model: "${OLLAMA_MODEL}"
    logging:
      type: pipeline.resources.structured_logging:StructuredLogging
      level: "INFO"
      file_enabled: true
      file_path: "logs/entity.log"
    memory:
      type: pipeline.resources.memory_resource:MemoryResource
      database:
<<<<<<< HEAD
        # DatabaseResource implementation
        type: pipeline.plugins.resources.sqlite_storage:SQLiteStorageResource
=======
        type: pipeline.resources.sqlite_storage:SQLiteStorageResource
>>>>>>> 31c26c6f08f011fda24b488de4c679ad0b2325fd
        path: ./agent.db
      filesystem:
        type: pipeline.resources.s3_filesystem:S3FileSystem
        bucket: agent-files
        region: us-east-1
  tools:
    weather:
      type: pipeline.plugins.tools.weather_api_tool:WeatherApiTool
      api_key: "${WEATHER_API_KEY}"
      base_url: "https://api.weather.com"
    calculator:
      type: pipeline.plugins.tools.calculator_tool:CalculatorTool
  adapters:
    http:
      type: pipeline.adapters.http:HTTPAdapter
    cli:
      type: pipeline.adapters.cli:CLIAdapter
  prompts:
    chain_of_thought:
      type: pipeline.plugins.prompts.chain_of_thought:ChainOfThoughtPrompt
      enable_reasoning: true
    memory_retrieval:
      type: pipeline.plugins.prompts.memory_retrieval:MemoryRetrievalPrompt
      max_context_length: 4000
    intent_classifier:
      type: pipeline.plugins.prompts.intent_classifier:IntentClassifierPrompt
      confidence_threshold: 0.8
