server:
  host: "0.0.0.0"
  port: 8000
  reload: true
  log_level: "info"

plugins:
  resources:
    database:
      type: plugins.postgres:PostgresResource
      host: "${DB_HOST}"
      port: 5432
      name: "${DB_USERNAME}"
      username: "${DB_USERNAME}"
      password: "${DB_PASSWORD}"
    llm:
      provider: ollama
      base_url: "${OLLAMA_BASE_URL}"
      model: "${OLLAMA_MODEL}"
    logging:
      type: plugins.structured_logging:StructuredLogging
      level: "INFO"
      file_enabled: true
      file_path: "logs/entity.log"
    memory:
      type: plugins.memory_resource:MemoryResource
      database:
        type: plugins.sqlite_storage:SQLiteStorageResource
        path: ./agent.db
      filesystem:
        type: plugins.s3_filesystem:S3FileSystem
        bucket: agent-files
        region: us-east-1
    cache:
      type: plugins.resources.cache:CacheResource
      backend:
        type: pipeline.cache.memory:InMemoryCache
  tools:
    weather:
      type: plugins.tools.weather_api_tool:WeatherApiTool
      api_key: "${WEATHER_API_KEY}"
      base_url: "https://api.weather.com"
    calculator:
      type: plugins.tools.calculator_tool:CalculatorTool
  adapters:
    http:
      type: pipeline.adapters.http:HTTPAdapter
      auth_tokens:
        - ${HTTP_TOKEN}
      rate_limit:
        requests: 60
        interval: 60
      audit_log_path: logs/audit.log
    cli:
      type: pipeline.adapters.cli:CLIAdapter
  prompts:
    chain_of_thought:
      type: plugins.prompts.chain_of_thought:ChainOfThoughtPrompt
      enable_reasoning: true
    memory_retrieval:
      type: plugins.prompts.memory_retrieval:MemoryRetrievalPrompt
      max_context_length: 4000
    intent_classifier:
      type: plugins.prompts.intent_classifier:IntentClassifierPrompt
      confidence_threshold: 0.8
