# flake8: noqa
# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: llm.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 0, "", "llm.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\tllm.proto\x12\x0b\x65ntity.grpc"!\n\x0fGenerateRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t"!\n\x10GenerateResponse\x12\r\n\x05token\x18\x01 \x01(\t2W\n\nLLMService\x12I\n\x08Generate\x12\x1c.entity.grpc.GenerateRequest\x1a\x1d.entity.grpc.GenerateResponse0\x01\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "llm_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_GENERATEREQUEST"]._serialized_start = 26
    _globals["_GENERATEREQUEST"]._serialized_end = 59
    _globals["_GENERATERESPONSE"]._serialized_start = 61
    _globals["_GENERATERESPONSE"]._serialized_end = 94
    _globals["_LLMSERVICE"]._serialized_start = 96
    _globals["_LLMSERVICE"]._serialized_end = 183
# @@protoc_insertion_point(module_scope)
