"""Plugins package for the Entity pipeline.

This module re-exports the core plugin base classes from
``plugins.contrib`` for convenience::

    from plugins import BasePlugin, ToolPlugin
"""

from .contrib import (
    AdapterPlugin,
    AutoGeneratedPlugin,
    BasePlugin,
    FailurePlugin,
    PromptPlugin,
    ResourcePlugin,
    ToolPlugin,
)

__all__ = [
    "AdapterPlugin",
    "AutoGeneratedPlugin",
    "BasePlugin",
    "FailurePlugin",
    "PromptPlugin",
    "ResourcePlugin",
    "ToolPlugin",
]
