"""Defines common plugin interfaces."""

import inspect
from importlib import import_module
from typing import Any, Dict, Optional, Type, cast

# Plugin base classes are injected at runtime to avoid hard dependencies on the
# pipeline package. They default to ``object`` until configured by the
# application.
BasePluginType: Type = object
PromptPluginType: Type = object
AdapterPluginType: Type = object
AutoGeneratedPluginType: Type = object


def configure_plugins(
    base_plugin: Type,
    prompt_plugin: Type,
    adapter_plugin: Type,
    auto_plugin: Type,
) -> None:
    """Configure concrete plugin base classes used for auto classification."""

    global BasePluginType, PromptPluginType, AdapterPluginType, AutoGeneratedPluginType
    BasePluginType = base_plugin
    PromptPluginType = prompt_plugin
    AdapterPluginType = adapter_plugin
    AutoGeneratedPluginType = auto_plugin


def import_plugin_class(path: str) -> Type:
    """Import plugin class from ``path``."""
    if ":" in path:
        module_path, class_name = path.split(":", 1)
    elif "." in path:
        module_path, class_name = path.rsplit(".", 1)
    else:
        raise ValueError(f"Invalid plugin path: {path}")
    module = import_module(module_path)
    return getattr(module, class_name)


class PluginAutoClassifier:
    """Utility to generate plugin classes from async functions."""

    @staticmethod
    def classify(
        plugin_func: Any, user_hints: Optional[Dict[str, Any]] | None = None
    ) -> Any:
        """Return a generated plugin class for ``plugin_func``."""

        from pipeline.stages import PipelineStage

        if not inspect.iscoroutinefunction(plugin_func):
            raise TypeError(
                f"Plugin function '{getattr(plugin_func, '__name__', 'unknown')}' must be async"
            )

        hints = user_hints or {}
        try:
            source = inspect.getsource(plugin_func)
        except OSError:
            source = ""

        if any(k in source for k in ["think", "reason", "analyze"]):
            stage = PipelineStage.THINK
            base = cast(Type, PromptPluginType)
        elif any(k in source for k in ["parse", "validate", "check"]):
            stage = PipelineStage.PARSE
            base = cast(Type, AdapterPluginType)
        elif any(k in source for k in ["return", "response", "answer"]):
            stage = PipelineStage.DO
            base = cast(Type, PromptPluginType)
        else:
            stage = PipelineStage.DO
            base = cast(Type, PromptPluginType)

        if "stage" in hints:
            stage = PipelineStage.from_str(str(hints["stage"]))

        priority = int(hints.get("priority", 50))
        name = hints.get("name", plugin_func.__name__)

        return AutoGeneratedPluginType(
            func=plugin_func,
            stages=[stage],
            priority=priority,
            name=name,
            base_class=base,
        )

    @staticmethod
    def classify_and_route(
        plugin_func: Any, user_hints: Optional[Dict[str, Any]] | None = None
    ) -> Any:
        return PluginAutoClassifier.classify(plugin_func, user_hints)


__all__ = ["PluginAutoClassifier", "import_plugin_class"]
