"""Public plugin base classes.

This module re-exports the core plugin primitives for external plugin authors.
Import from :mod:`entity.plugins.base` instead of :mod:`entity.core.plugins`.
"""

from ..core.plugins import (
    AdapterPlugin,
    AgentResource,
    AutoGeneratedPlugin,
    BasePlugin,
    ConfigurationError,
    FailurePlugin,
    InfrastructurePlugin,
    InputAdapterPlugin,
    OutputAdapterPlugin,
    Plugin,
    PluginAutoClassifier,
    PromptPlugin,
    ReconfigResult,
    ResourcePlugin,
    ToolExecutionError,
    ToolPlugin,
    ValidationResult,
)

__all__ = [
    "AdapterPlugin",
    "AgentResource",
    "AutoGeneratedPlugin",
    "BasePlugin",
    "ConfigurationError",
    "FailurePlugin",
    "InfrastructurePlugin",
    "InputAdapterPlugin",
    "OutputAdapterPlugin",
    "Plugin",
    "PluginAutoClassifier",
    "PromptPlugin",
    "ReconfigResult",
    "ResourcePlugin",
    "ToolExecutionError",
    "ToolPlugin",
    "ValidationResult",
]
