name: Quality Checks

on:
  pull_request:
    paths-ignore:
      - 'docs/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install poetry
      - run: poetry install --with dev
      - run: python docs/generate_config_docs.py --check
      - run: black --check src tests
      - run: isort --check-only src tests
      - run: flake8 src tests
      - run: mypy src
      - run: pydocstyle src
