name: Quality Checks

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'src/docs_build/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install black isort flake8 mypy pydocstyle
      - run: black --check src tests
      - run: isort --check-only src tests
      - run: flake8 src tests
      - run: mypy src
      - run: pydocstyle src
