name: Test

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: snok/install-poetry@v1
      - name: Install deps
        run: poetry install --with dev
      - name: Run tests
        env:
          ENTITY_AUTO_INSTALL_OLLAMA: 'true'
        run: |
          poetry run poe test
          poetry run poe test-with-docker
      - name: Run plugin tests
        run: |
          poetry run pytest tests/plugins/ -v
      - name: Build documentation (verify plugin docs)
        run: |
          poetry run sphinx-build -W -b html docs/source docs/build
